name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # Use only default interpreter, no third-party packages are used
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

        # GitHub Actions automatically fails the job if the script exits with a non-zero code
      - name: Run Python script
        run: |
          python3 test/test_suite.py
