name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use python 3.12, no third-party packages
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

        # GitHub Actions automatically fails the job if the script exits with a non-zero code
      - name: Run tests, failure if non-zero exit code
        run: |
          python3 test/test_suite.py

      - name: Display test results
        run: cat test_results.txt

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.txt
